WIDTH = 640
HEIGHT = 480
FPS = 120

BG_SCALE = HEIGHT / 1024
TOP_LANE_Y = 272 * BG_SCALE
BOTTOM_LANE_Y = 50 * BG_SCALE
MTS_TO_PIXELS = WIDTH / 10
ACC = 7  # mt/s^2
X_ACC = ACC * MTS_TO_PIXELS     # pixels/s^2?
COLLISION_ACC = -2 * MTS_TO_PIXELS

TREE_FOOTPRINT = 1.5
TREE_OFFSET = 0.3
TREE_PROB = 0.65

ROCKS_FOOTPRNT = 6
ROCKS_OFFSET = 1
ROCKS_PROB = 0.6

LVL_LENGTH = 300
PARTITION_SIZE = 20

SKY_PARALLAX = 0.25
BG_LOOP_POINT = 1024
SKY_LOOP_POINT = 1024

# Sounds
HIT = 'h'
PADDLE = 'p'
MUSIC = 'm'
BACKGROUND = 'b'

GLOBAL_VOLUME = 1
MUSIC_VOLUME = 0.8
